### ISSUE TITLE
Doesn't seem to work for me using the test.png file

### ISSUE THREAD

**Issue by jrgleason** [antimatter15/ocrad.js#19]
I went to the page http://antimatter15.com/ocrad.js/demo.html. I try to drag and drop the test.png from the examples folder. It shows...

    Cannot enlarge memory arrays in asm.js. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, or (2) set Module.TOTAL_MEMORY before the program runs.
     ocrad.js:7985 Uncaught abort() at Error
       at stackTrace (http://antimatter15.com/ocrad.js/ocrad.js:935:15)
       at abort (http://antimatter15.com/ocrad.js/ocrad.js:7985:25)

**Comment by adadgio** [comment]
Any update on the issue ? I am having the same problem, maybe our images are too large ?

**Comment by kba** [comment]
Cannot reproduce. If I download https://github.com/antimatter15/ocrad.js/blob/master/examples/nodejs/test.png and drag it to http://antimatter15.com/ocrad.js/demo.html, recognition works fine (well, ocrad-fine).

Also, it's weird that the error message states that memory is limited to 16MB since the build.sh sets `TOTAL_MEMORY` to 32MB.

Could be a browser thing? Tried it in Win 10 Chrome 68.0.3440.75.

**Comment by adadgio** [comment]
I am trying from nodeJS on my side. I don't think this isan OCRAD issue though.... More avout reading very big buffer array from javscript , client side or server side.
